// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw9FRS3ybdrSFAHRxudxZsW8tSidCzB-4',
    appId: '1:717557822486:web:4f5bec955ec316e3cef137',
    messagingSenderId: '717557822486',
    projectId: 'forgemate-2ce4f',
    authDomain: 'forgemate-2ce4f.firebaseapp.com',
    storageBucket: 'forgemate-2ce4f.firebasestorage.app',
    measurementId: 'G-F606QRF5WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFWYDzpIWGsOqJ5arVLpTvnpTX4f5pIU',
    appId: '1:717557822486:android:ff723ff3420f3bd4cef137',
    messagingSenderId: '717557822486',
    projectId: 'forgemate-2ce4f',
    storageBucket: 'forgemate-2ce4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0bp2yJglUcwBPhUuzV4sRttsnY9AFN8',
    appId: '1:717557822486:ios:cafadfaf610c4423cef137',
    messagingSenderId: '717557822486',
    projectId: 'forgemate-2ce4f',
    storageBucket: 'forgemate-2ce4f.firebasestorage.app',
    iosBundleId: 'com.example.forgemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy0bp2yJglUcwBPhUuzV4sRttsnY9AFN8',
    appId: '1:717557822486:ios:cafadfaf610c4423cef137',
    messagingSenderId: '717557822486',
    projectId: 'forgemate-2ce4f',
    storageBucket: 'forgemate-2ce4f.firebasestorage.app',
    iosBundleId: 'com.example.forgemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw9FRS3ybdrSFAHRxudxZsW8tSidCzB-4',
    appId: '1:717557822486:web:de056958f1602bd0cef137',
    messagingSenderId: '717557822486',
    projectId: 'forgemate-2ce4f',
    authDomain: 'forgemate-2ce4f.firebaseapp.com',
    storageBucket: 'forgemate-2ce4f.firebasestorage.app',
    measurementId: 'G-573QRPSS52',
  );

}